#!/bin/bash
read -p "ID: " id
curl -s -o o17.html https://zsem.edu.pl/plany/plany/$id.html
grep -E '&nbsp|class="g"|class="p"|<th' o17.html | 
sed "
s/.*p\">/|/g;
s/<\/.*s\">/ /g;
s/<\/a*.*/|/g;
s/.*g\">//g;
s/.*&nbsp;/|-/g;
s/<th>/|/g;
s/|Nr|//g;
0,/ *|/{s/ *|//}
" > ~/.cache/o17
sed ':a;N;$!ba;s/\n/\t/g ; s/..:..-..:../\n& /g' ~/.cache/o17 |
column -t -s "|"
rm ~/.cache/o17

# ok prawie dziala ale nie pokazuje niemieckiego, dwoch matm i historii w piatek, z jakiegos powodu XD
# plus wyswietla tylko druga grupe
# no i naglowki kolumn sa przesuniete o ilestam spacji
